In [111]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: numpy in C:\ProgramData\anaconda3\Lib\site-packages (2.4.6)
Note: you may need to restart the kernel to use updated packages.

In [112]:
import numpy as np

In [113]:
##Create a 1D NumPy Array:

temperatures_w1=np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

In [114]:
##Inspection and Properties:

temperatures_w1.shape

(7,)

In [115]:
temperatures_w1.dtype

dtype('float64')

In [116]:
temperatures_w1.size

7

In [7]:
temperatures_w1.ndim

1

In [11]:
## Array Operations:


temperatures_w1_faren = (temperatures_w1 * 9/5) + 32
print(temperatures_w1_faren)

[72.5  77.54 69.44 74.12 78.98 76.64 71.42]

In [18]:
##Find the maximum, minimum, and mean temperatures for the week.

max_temp=np.max(temperatures_w1)
min_temp=np.min(temperatures_w1)
mean_temp=np.mean(temperatures_w1)
print("Max temparature:",max_temp)
print("Min temparature:",min_temp)
print("Mean temparature:",mean_temp)

Max temparature: 26.1
Min temparature: 20.8
Mean temparature: 23.542857142857144

In [22]:
##Array Slicing and Index

first_three=temperatures_w1[0:3]
last_two=temperatures_w1[-2:]
middle_two=temperatures_w1[2:5]
print("Temparature of first three days:",first_three)
print("Temparature of last two days:",last_two)
print("Temparature of middle two days:",middle_two)

Temparature of first three days: [22.5 25.3 20.8]
Temparature of last two days: [24.8 21.9]
Temparature of middle two days: [20.8 23.4 26.1]

In [30]:
##5. Create a 2D Array:

temperatures=np.array([[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],
                      [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]])

In [33]:
temperatures

array([[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],
       [19.2, 22.5, 21.3, 24. , 23.5, 22.8, 20.1]])

In [34]:
##6. Inspect and Slice the 2D Array:

temperatures.shape

(2, 7)

In [35]:
temperatures.dtype

dtype('float64')

In [37]:
temperatures.size

14

In [51]:
##Extract the temperatures for each week and the weekends (last two days) for both weeks.

week1=temperatures[0]
weekend1=week1[-2:]
print(week1)
print(weekend1)

[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
[24.8 21.9]

In [54]:
week2=temperatures[1]
weekend2=week2[-2:]
print(week2)
print(weekend2)

[19.2 22.5 21.3 24.  23.5 22.8 20.1]
[22.8 20.1]

###Pandas Series:

In [119]:
##1. Creating Pandas Series:
import pandas as pd

In [130]:
marks=pd.Series(
    data=[95,92,89,85,80],
    index=["Rank1","Rank2","Rank3","Rank4","Rank5"]
)

In [131]:
marks

Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64

In [132]:
#2. Indexing and Slicing:

print("Mark of 1st rank syudent:",marks["Rank1"])

Mark of 1st rank syudent: 95

In [133]:
#.Marks of the top 3 ranks

top_3=marks.loc["Rank1":"Rank3"]
print("Top 3 rankers are\n",top_3)

Top 3 rankers are
 Rank1    95
Rank2    92
Rank3    89
dtype: int64

In [134]:
#1.Mark of the 3rd rank student(USE ILOC)

rank3=marks.iloc[2]
print("Mark of the 3rd rank student:",rank3)

Mark of the 3rd rank student: 89

In [135]:
#2.Boolean mask - marks > 90

print("Rankers having marks greater than 90:\n",marks[marks>90])

Rankers having marks greater than 90:
 Rank1    95
Rank2    92
dtype: int64

In [136]:
##3. Manipulating Series:
##Modify the mark of the student with the 1st rank to 100

marks.loc["Rank1"]=100
print(marks)

Rank1    100
Rank2     92
Rank3     89
Rank4     85
Rank5     80
dtype: int64

In [137]:
##Remove the entry corresponding to the last rank from the Series

marks=marks.drop("Rank5")
print(marks)

Rank1    100
Rank2     92
Rank3     89
Rank4     85
dtype: int64

In [138]:
#Compute the CGPA by dividing each mark in the Series by 10.
marks = marks/10
print(marks)

Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
dtype: float64

In [59]:
##Pandas DataFrame:
import pandas as pd

In [60]:
data={"TransactionID":[101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
              "ProductCategory": ["Electronics","Clothing","Electronics","Furniture",
                                  "Clothing","Electronics","Furniture","Clothing","Furniture","Electronics"],
              "Region": ["North","South","North","East","West","North","East","West",
"South","North"],"Amount":[200, 150, 300, 450, 200, 250, 300, 180, 350, 400]}
transactions=pd.DataFrame(data)

In [1]:
##2. Data Exploration:
##Display the transactions DataFrame and its basic information, including head, tail, shape, column names, and data types.

In [61]:
print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

In [62]:
transactions.head()

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200

In [63]:
transactions.tail()

   TransactionID ProductCategory Region  Amount
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

In [64]:
transactions.shape

(10, 4)

In [65]:
transactions.dtypes

TransactionID      int64
ProductCategory      str
Region               str
Amount             int64
dtype: object

In [66]:
transactions.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   TransactionID    10 non-null     int64
 1   ProductCategory  10 non-null     str
 2   Region           10 non-null     str
 3   Amount           10 non-null     int64
dtypes: int64(2), str(2)
memory usage: 593.0 bytes

In [67]:
transactions.columns

Index(['TransactionID', 'ProductCategory', 'Region', 'Amount'], dtype='str')

In [21]:
##● Display only the 'ProductCategory' and 'Amount' columns

In [68]:
transactions[["ProductCategory","Amount"]]

  ProductCategory  Amount
0     Electronics     200
1        Clothing     150
2     Electronics     300
3       Furniture     450
4        Clothing     200
5     Electronics     250
6       Furniture     300
7        Clothing     180
8       Furniture     350
9     Electronics     400

In [28]:
##● Retrieve the last 3 columns of the DataFrame using iloc or loc.

In [69]:
transactions.iloc[:,-3:]

  ProductCategory Region  Amount
0     Electronics  North     200
1        Clothing  South     150
2     Electronics  North     300
3       Furniture   East     450
4        Clothing   West     200
5     Electronics  North     250
6       Furniture   East     300
7        Clothing   West     180
8       Furniture  South     350
9     Electronics  North     400

In [35]:
##Filter rows where the 'Region' is 'North' and 'Amount' is greater than 200.

In [70]:
transactions[(transactions["Region"]=="North") & (transactions["Amount"] > 200)]

   TransactionID ProductCategory Region  Amount
2            103     Electronics  North     300
5            106     Electronics  North     250
9            110     Electronics  North     400

In [49]:
##Find the value counts for the 'ProductCategory' column.

In [72]:
transactions['ProductCategory'].value_counts()

ProductCategory
Electronics    4
Clothing       3
Furniture      3
Name: count, dtype: int64

In [54]:
##Find the unique values in the 'Region' column.

In [73]:
transactions["Region"].unique()

<ArrowStringArray>
['North', 'South', 'East', 'West']
Length: 4, dtype: str

In [59]:
##● Group by 'Region' and find the mean amount for each region.

In [74]:
transactions.groupby("Region") ["Amount"].mean()

Region
East     375.0
North    287.5
South    250.0
West     190.0
Name: Amount, dtype: float64

In [1]:
##3. Manipulating the DataFrame:

In [75]:
transactions.loc[transactions["TransactionID"] == 102, "Amount"] = 165

print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

In [32]:
##Add a new column 'Discount' by calculating 10% of the 'Amount'.

In [76]:
transactions["Discount"]=transactions["Amount"]*0.10
print(transactions)

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
8            109       Furniture  South     350      35.0
9            110     Electronics  North     400      40.0

In [12]:
##Remove the row with TransactionID 109

In [77]:
transactions.drop(transactions[transactions["TransactionID"] == 109].index,inplace=True)
print(transactions)

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
9            110     Electronics  North     400      40.0

In [43]:
## Delete the 'Discount' column from the DataFrame.

In [79]:
transactions = transactions.drop(columns=["Discount"])

print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
9            110     Electronics  North     400